### ISSUE TITLE
建议添加正则表达式功能

### ISSUE THREAD

**Issue by allmelgr** [phodal/growth-ng#43]
可以参考regexper.com中的设计，用过的人都说简单易懂

没提交过issues，感觉简直在捣乱。。。

**Comment by ivanberry** [comment]
[正则表达式参考](https://regex101.com/)

**Comment by phodal** [comment]
@allmelgr @ivanberry    功能用 WebView 实现，代码见：https://github.com/phodal/moregex 欢迎提反馈啊
