### ISSUE TITLE
请问安卓的包名ren.growth是手动修改的吗

### ISSUE THREAD

**Issue by entronad** [phodal/growth-ng#56]
请问项目是用react-native-cli脚手架初始化的吗？
如果是的话那安卓的包名该是com.growth
您这里的ren.growth是手动修改的还是有什么配置方法？

**Comment by phodal** [comment]
这个应该是之前重命名包出问题了

**Comment by entronad** [comment]
您本意不是想改成ren.growth的是吧
您知道有没有什么配置生成的包名（包括Android文件夹结构）的办法吗？还是必须像网上说的手动件文件夹

**Comment by phodal** [comment]
@entronad https://stackoverflow.com/questions/40281569/use-specific-package-name-when-setting-up-a-react-native-project

**Comment by entronad** [comment]
@phodal 谢谢

**Comment by entronad** [comment]
这个回答里的方法失效了，现在rn没有修改package的功能。。。
https://github.com/facebook/react-native/issues/12721
